version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-demo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-157ztc9w2jmvd"
s3_prefix = "sam-app-demo"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
